language: python
python:
  - "2.7"
sudo: true
cache:
  # Workaround for
  # https://github.com/travis-ci/travis-ci/issues/3239
  directories:
    - ~/.cache/pip
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
before_script:
  - flake8 . --exclude=./docs/conf.py
install:
  - DEB_HOST_MULTIARCH=x86_64-linux-gnu pip install -I --exists-action=w "git+git://anonscm.debian.org/collab-maint/m2crypto.git@debian/0.21.1-3#egg=M2Crypto"
  - pip install --find-links https://pyrepo.addons.mozilla.org/ peep
  - peep install --no-deps -r requirements/dev.txt --find-links https://pyrepo.addons.mozilla.org/
script: ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
